version: "3.3"

services:
  twigs:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      TWIGS_DB_HOST: db
      TWIGS_DB_TYPE: postgresql
    networks:
      - twigs

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: twigs
      POSTGRES_USER: twigs
      POSTGRES_PASSWORD: twigs
    networks:
      - twigs
    hostname: db

networks:
  twigs:
