version: "3.3"

services:
  twigs:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/budget?useSSL=false"
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SERVER_TOMCAT_MAX-THREADS: 5
      TWIGS_CORS_DOMAINS: "http://localhost:4200"
    networks:
      - twigs
    command: sh -c "sleep 5 && /opt/java/openjdk/bin/java $JVM_ARGS -jar /twigs-api.jar"

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: budget
      MYSQL_USER: budget
      MYSQL_PASSWORD: budget
    networks:
      - twigs
    hostname: db

networks:
  twigs:
