version: "3.3"

services:
  twigs:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgres://db:5432/twigs"
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SERVER_TOMCAT_MAX-THREADS: 5
      TWIGS_CORS_DOMAINS: "http://localhost:4200"
    networks:
      - twigs
    command: sh -c "sleep 5 && /opt/java/openjdk/bin/java $JVM_ARGS -jar /twigs-api.jar"

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: twigs
      POSTGRES_USER: twigs
      POSTGRES_PASSWORD: twigs
    networks:
      - twigs
    hostname: db

networks:
  twigs:
